# Generated by Django 4.0.4 on 2022-06-12 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('DistrictID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DistrictName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('StateID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('StateName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('TalukID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TalukName', models.CharField(max_length=50)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('VillageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('VillageName', models.CharField(max_length=50)),
                ('Taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.taluk')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.state'),
        ),
    ]
