# Generated by Django 4.0.4 on 2022-08-07 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('BankID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('BankName', models.CharField(max_length=50)),
                ('OrderID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('OnlineID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OnlineAppName', models.CharField(max_length=50)),
                ('OrderID', models.IntegerField()),
            ],
        ),
    ]
