# Generated by Django 4.0.4 on 2022-06-16 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dshiksha_erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('AcademicYearID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AcademicYear', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField()),
                ('OrderID', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('AreaID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AreaType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('BloodGroupID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('BloodGroupName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CasteCategory',
            fields=[
                ('CasteCategoryID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CasteCategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('ClassLevelID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ClassLevelName', models.CharField(max_length=50)),
                ('ClassLevelCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('ClassID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=50)),
                ('OrderID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('DesignationID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DesignationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('FeesTypeID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('FeesTypeName', models.CharField(max_length=50)),
                ('FeeTypeCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('GenderID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('GenderName', models.CharField(max_length=50)),
                ('GenderOrder', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('InstallmentID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('InstallmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionLevel',
            fields=[
                ('InstitutionLevelID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('InstitutionLevel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('MaritalStatusID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MaritalStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediumOfInstruction',
            fields=[
                ('MediumOfInstructionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MediumOfInstruction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('ModeOfPaymentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ModeOfPayment', models.CharField(max_length=50)),
                ('OrderID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MotherTongue',
            fields=[
                ('MotherTongueID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MotherTongueName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('NationalityID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NationalityName', models.CharField(max_length=50)),
                ('CountryCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('ParishID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ParishName', models.CharField(max_length=50)),
                ('ParishArea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('PaymentStatusID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PaymentStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('PostOfficeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PostOfficeName', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('ReligionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ReligionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SectionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SectionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProQualification',
            fields=[
                ('StaffProQualificationID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('StaffProQualificationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('StaffQualificationID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('StaffQualificationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSubject',
            fields=[
                ('StaffSubjectID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('StaffSubjectName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusType',
            fields=[
                ('SyllabusTypeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SyllabusType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubFee',
            fields=[
                ('SubFeeID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('SubFeeName', models.CharField(max_length=50)),
                ('FeesType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.feestype')),
            ],
        ),
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('CorrespondentID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('CorrespondentFirstName', models.CharField(max_length=100)),
                ('CorrespondentLastName', models.CharField(max_length=100, null=True)),
                ('CorrespondentEmail', models.EmailField(max_length=100)),
                ('CorrespondentMobile', models.CharField(max_length=100)),
                ('CorrespondentWhatsAppNo', models.CharField(max_length=100)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLevelFees',
            fields=[
                ('ClassLevelFeesID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ClassLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.classlevel')),
                ('FeesType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.feestype')),
            ],
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('CasteID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CasteName', models.CharField(max_length=50)),
                ('CasteCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.castecategory')),
                ('Religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.religion')),
            ],
        ),
    ]
