# Generated by Django 4.0.4 on 2022-08-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0002_feedback_installment_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoffice',
            name='Pincode',
            field=models.CharField(max_length=6),
        ),
    ]
