# Generated by Django 4.0.4 on 2022-07-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_parish'),
        ('dshiksha_erp', '0002_academicyear_area_bloodgroup_castecategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parish',
        ),
    ]
