# Generated by Django 4.0.4 on 2022-08-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0004_alter_postoffice_pincode'),
    ]

    operations = [

    ]
