from django.contrib import admin
from . import models as md

# Register your models here.
admin.site.register(md.AcademicYear)
admin.site.register(md.Area)
admin.site.register(md.State)
admin.site.register(md.District)
admin.site.register(md.Taluk)
admin.site.register(md.Village)
admin.site.register(md.Gender)
admin.site.register(md.Nationality)
admin.site.register(md.MotherTongue)
admin.site.register(md.BloodGroup)
admin.site.register(md.StaffQualification)
admin.site.register(md.Religion)
admin.site.register(md.CasteCategory)
admin.site.register(md.Caste)
admin.site.register(md.ClassLevel)
admin.site.register(md.ClassList)
admin.site.register(md.Section)
admin.site.register(md.FeesType)
admin.site.register(md.SubFee)
admin.site.register(md.Installment)
admin.site.register(md.PostOffice)
admin.site.register(md.InstitutionLevel)
admin.site.register(md.ModeOfPayment)
admin.site.register(md.StaffSubject)
admin.site.register(md.MaritalStatus)
admin.site.register(md.Bank)
admin.site.register(md.Online)
admin.site.register(md.Feedback)
