# Generated by Django 4.0.4 on 2022-08-06 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CBSEHead',
            new_name='SCHOOLHead',
        ),
        migrations.RemoveField(
            model_name='schoolhead',
            name='CBSEHeadID',
        ),
        migrations.AddField(
            model_name='schoolhead',
            name='SCHOOLHeadID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
