# Generated by Django 4.0.4 on 2022-08-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectfee',
            name='CollectFeeDate',
            field=models.DateField(null=True),
        ),
    ]
