# Generated by Django 4.0.4 on 2022-08-18 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectFee',
            fields=[
                ('CollectFeeID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('RefferenceNO', models.CharField(max_length=100, null=True)),
                ('PaidAmount', models.FloatField()),
                ('PaymentStatus', models.CharField(max_length=100, null=True)),
                ('CollectFeeDate', models.DateField()),
                ('CollectFeeNo', models.CharField(max_length=100)),
                ('Admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students')),
                ('AssignClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.assignclass')),
                ('Bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.bank')),
                ('Installment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.installment')),
                ('ModeOfPayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.modeofpayment')),
                ('Online', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.online')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='AssignFeeAmount',
            fields=[
                ('AssignFeeAmountID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('AcademicYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.academicyear')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('FeesType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.feestype')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('SubFee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.subfee')),
            ],
        ),
    ]
