# Generated by Django 4.0.4 on 2022-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='FatherEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='FatherMobileNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='FatherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='FatherOccupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='FatherQualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='FatherWhatsappNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianMobileNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianOccupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianQualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianWhatsappNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherMobileNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherOccupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherQualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherWhatsappNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
