# Generated by Django 4.0.4 on 2022-08-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_students_fatheremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='AssignedClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.assignclass'),
        ),
    ]
