# Generated by Django 4.0.4 on 2022-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_correspondentfirstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='StaffWhatsAppNo',
            field=models.CharField(max_length=10),
        ),
    ]
