# Generated by Django 4.0.4 on 2022-08-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_cbsehead_schoolhead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='CautionDeposit',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='ESI',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Gratuity',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='ProfessionalTax',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='ProvidentFund',
        ),
    ]
