# Generated by Django 4.0.4 on 2022-08-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0002_bank_online'),
        ('school', '0002_remove_students_assignclass_students_assignedclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectfee',
            name='AssignClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.assignclass'),
        ),
        migrations.AlterField(
            model_name='collectfee',
            name='Installment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.installment'),
        ),
        migrations.AlterField(
            model_name='collectfee',
            name='ModeOfPayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.modeofpayment'),
        ),
        migrations.AlterField(
            model_name='collectfee',
            name='PaymentStatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
