# Generated by Django 4.0.4 on 2022-07-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0003_delete_parish'),
        ('school', '0002_remove_school_parish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='AcademicYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.academicyear'),
        ),
    ]
