# Generated by Django 4.0.4 on 2022-08-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0002_bank_online'),
        ('school', '0003_remove_staff_cautiondeposit_remove_staff_esi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.gender'),
        ),
    ]
