# Generated by Django 4.0.4 on 2022-08-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_students_assignedclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.application'),
        ),
    ]
