# Generated by Django 4.0.4 on 2022-08-07 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0001_initial'),
        ('school', '0003_remove_staff_cautiondeposit_remove_staff_esi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('AdmissionID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('AdmissionNo', models.CharField(max_length=100)),
                ('AdmissionDate', models.DateField()),
                ('PreviousSchoolName', models.CharField(max_length=100)),
                ('StudentPhoto', models.CharField(max_length=100)),
                ('StudentName', models.CharField(max_length=100)),
                ('StudentDOB', models.DateField()),
                ('StudentMobileNo', models.CharField(max_length=30)),
                ('AddressLine1', models.CharField(max_length=100)),
                ('AddressLine2', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=100)),
                ('FatherMobileNo', models.CharField(max_length=100)),
                ('FatherWhatsappNo', models.CharField(max_length=100)),
                ('FatherEmail', models.EmailField(max_length=100)),
                ('FatherQualification', models.CharField(max_length=100)),
                ('FatherOccupation', models.CharField(max_length=100)),
                ('FatherIncome', models.FloatField()),
                ('MotherName', models.CharField(max_length=100)),
                ('MotherMobileNo', models.CharField(max_length=100)),
                ('MotherWhatsappNo', models.CharField(max_length=100)),
                ('MotherEmail', models.EmailField(max_length=100)),
                ('MotherQualification', models.CharField(max_length=100)),
                ('MotherOccupation', models.CharField(max_length=100)),
                ('MotherIncome', models.FloatField()),
                ('GuardianName', models.CharField(max_length=100)),
                ('GuardianMobileNo', models.CharField(max_length=100)),
                ('GuardianWhatsappNo', models.CharField(max_length=100)),
                ('GuardianEmail', models.EmailField(max_length=100)),
                ('GuardianQualification', models.CharField(max_length=100)),
                ('GuardianOccupation', models.CharField(max_length=100)),
                ('GuardianIncome', models.FloatField()),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.application')),
                ('BloodGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.bloodgroup')),
                ('Caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.caste')),
                ('CasteCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.castecategory')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.gender')),
                ('MotherTongue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.mothertongue')),
                ('Nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.nationality')),
                ('Pincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.postoffice')),
                ('Religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.religion')),
                ('SchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('Village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.village')),
            ],
        ),
    ]
