# Generated by Django 4.0.4 on 2022-07-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0003_delete_parish'),
        ('school', '0003_alter_staff_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='InsitutionLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.institutionlevel'),
        ),
    ]
