# Generated by Django 4.0.4 on 2022-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_collectfee_collectfeedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='PreviousSchoolName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
