# Generated by Django 4.0.4 on 2022-08-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_staff_staffwhatsappno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ParentMobileNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='StudentMobileNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='FatherMobileNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='FatherWhatsappNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianMobileNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianWhatsappNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherMobileNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherWhatsappNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='StudentMobileNo',
            field=models.CharField(max_length=10),
        ),
    ]
