# Generated by Django 4.0.4 on 2022-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_collectfee_assignclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectfee',
            name='AdmissionDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectfee',
            name='PaidAmount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
