# Generated by Django 4.0.4 on 2022-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_collectfee_admissiondate_alter_collectfee_paidamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectfee',
            name='AdmissionDate',
        ),
        migrations.AddField(
            model_name='collectfee',
            name='CollectFeeDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectfee',
            name='CollectFeeNo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
