# Generated by Django 4.0.4 on 2022-08-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0001_initial'),
        ('school', '0004_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.nationality'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.religion'),
        ),
    ]
