# Generated by Django 4.0.4 on 2022-08-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_correspondentfirstname_school_correspondentname_and_more'),
    ]

    operations = [

    ]
