# Generated by Django 4.0.4 on 2022-07-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_school_insitutionlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffNo',
        ),
    ]
