# Generated by Django 4.0.4 on 2022-08-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_attendances'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendances',
            new_name='Attendance',
        ),
    ]
