# Generated by Django 4.0.4 on 2022-08-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0001_initial'),
        ('school', '0005_alter_students_nationality_alter_students_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Caste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.caste'),
        ),
        migrations.AlterField(
            model_name='students',
            name='CasteCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.castecategory'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.nationality'),
        ),
    ]
