# Generated by Django 4.0.4 on 2022-08-05 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0003_delete_parish'),
        ('school', '0005_delete_staffno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ApplicationNo', models.CharField(max_length=100)),
                ('StudentName', models.CharField(max_length=100)),
                ('StudentDOB', models.DateField()),
                ('StudentMobileNo', models.CharField(max_length=30)),
                ('ParentName', models.CharField(max_length=100)),
                ('ParentMobileNo', models.CharField(max_length=30)),
                ('ApplicationDate', models.DateField()),
                ('Amount', models.FloatField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.gender')),
                ('ModeOfPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.modeofpayment')),
                ('SchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
