# Generated by Django 4.0.4 on 2022-08-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_collectfee_admissiondate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectFee',
        ),
    ]
