# Generated by Django 4.0.4 on 2022-08-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0002_feedback_installment_orderid'),
        ('school', '0005_rename_correspondentfirstname_school_correspondentname_and_more'),
    ]

    operations = [


        migrations.AlterField(
            model_name='school',
            name='SchoolCode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='school',
            name='SchoolDISECode',
            field=models.CharField(max_length=11),
        ),
    ]
