# Generated by Django 4.0.4 on 2022-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_school_gstino_remove_school_schoolpanno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Landline',
            field=models.CharField(max_length=10),
        ),

    ]
