# Generated by Django 4.0.4 on 2022-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_students_caste_alter_students_castecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='FatherIncome',
            field=models.FloatField(null=True),
        ),
    ]
