# Generated by Django 4.0.4 on 2022-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_students_fathername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='FatherName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='GaurdianName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
