# Generated by Django 4.0.4 on 2022-08-16 06:46

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_attendances_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='StaffPhoto',
            field=models.ImageField(null=True, upload_to=school.models.filepath_staff),
        ),
    ]
