# Generated by Django 4.0.4 on 2022-08-16 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0002_bank_online'),
        ('school', '0006_delete_collectfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectFee',
            fields=[
                ('CollectFeeID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('RefferenceNO', models.CharField(max_length=100, null=True)),
                ('PaidAmount', models.FloatField()),
                ('PaymentStatus', models.CharField(max_length=100, null=True)),
                ('CollectFeeDate', models.DateField()),
                ('CollectFeeNo', models.CharField(max_length=100)),
                ('Admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students')),
                ('AssignClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.assignclass')),
                ('Bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.bank')),
                ('Installment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.installment')),
                ('ModeOfPayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.modeofpayment')),
                ('Online', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dshiksha_erp.online')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
