# Generated by Django 4.0.4 on 2022-08-16 13:25

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_staff_staffphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='SchoolSeal',
            field=models.ImageField(null=True, upload_to=school.models.filepath_school),
        ),
        migrations.AddField(
            model_name='school',
            name='SchoolSign',
            field=models.ImageField(null=True, upload_to=school.models.filepath_school),
        ),
        migrations.AlterField(
            model_name='school',
            name='SchoolLogo',
            field=models.ImageField(null=True, upload_to=school.models.filepath_school),
        ),
        migrations.AlterField(
            model_name='students',
            name='StudentPhoto',
            field=models.ImageField(null=True, upload_to=school.models.filepath_student),
        ),
    ]
