# Generated by Django 4.0.4 on 2022-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_students_fatherincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='GuardianIncome',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='MotherIncome',
            field=models.FloatField(null=True),
        ),
    ]
