# Generated by Django 4.0.4 on 2022-08-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0002_feedback_installment_orderid'),
        ('school', '0007_rename_correspondentfirstname_school_correspondentname_and_more'),
    ]

    operations = [
        
    ]
