# Generated by Django 4.0.4 on 2022-08-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_students_fathername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='CorrespondentFirstName',
            new_name='CorrespondentName',
        ),
        migrations.RemoveField(
            model_name='school',
            name='CorrespondentLastName',
        ),
    ]
