# Generated by Django 4.0.4 on 2022-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_correspondentfirstname_school_correspondentname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
