# Generated by Django 4.0.4 on 2022-08-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_students_guardianincome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='GuardianEmail',
            new_name='GaurdianEmail',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='GuardianIncome',
            new_name='GaurdianIncome',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='GuardianMobileNo',
            new_name='GaurdianMobileNo',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='GuardianName',
            new_name='GaurdianName',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='GuardianOccupation',
            new_name='GaurdianOccupation',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='GuardianQualification',
            new_name='GaurdianQualification',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='GuardianWhatsappNo',
            new_name='GaurdianWhatsappNo',
        ),
    ]
