# Generated by Django 4.0.4 on 2022-08-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_school_schoolseal_school_schoolsign_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
