# Generated by Django 4.0.4 on 2022-08-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0002_feedback_installment_orderid'),
        ('school', '0009_alter_school_mobile'),
    ]

    operations = [

        migrations.AlterField(
            model_name='school',
            name='AccountantMobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='AccountantWhatsAppNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='CorrespondentMobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='CorrespondentWhatsAppNo',
            field=models.CharField(max_length=10),
        ),

    ]
