# Generated by Django 4.0.4 on 2022-08-25 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshiksha_erp', '0003_alter_postoffice_pincode'),
        ('school', '0010_rename_correspondentfirstname_school_correspondentname_and_more'),
    ]

    operations = [
        
    ]
